version: '3.5'

# this docker compose file creates the various services used across all dev platforms at plusForta, including
# * traefik (w/Jaeger)
# * memcached
# * redis
# * mailhog
# * mysql
services:
  memcached:
    container_name: memcached
    image: memcached:alpine
    networks:
      - internal
    restart: unless-stopped
  redis:
    image: redis
    networks:
      - internal
    ports:
      - "6380:6379"
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - internal
    ports:
      - "3316:3306"
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    restart: unless-stopped
  mailhog:
    container_name: mailhog
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"
    networks:
      - internal
    restart: unless-stopped
  traefik:
    container_name: traefik
    image: traefik:v2.0
    restart: unless-stopped
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
      AWS_HOSTED_ZONE_ID: ${AWS_ZONE_ID}
      AWS_REGION: "eu-central-1"
    ports:
      - 80:80
      - 443:443
      - 8082:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/traefik.yml:/etc/traefik.yml
      - acmedata:/acme
    networks:
      - web
volumes:
  acmedata: # storage for acme.json from traefik
  dbdata:  # contains mariadb database
networks:
  web: # defines the network used to connect to traefik in another container
    name: web
  internal: # defines the network used to connect to all services
    name: internal
